# Generated by Django 6.0.5 on 2026-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('P', 'Planta'), ('E', 'Electrico'), ('L', 'Lagartija'), ('S', 'Psíquico')], max_length=30),
        ),
    ]
