# Generated by Django 4.2 on 2026-06-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(default='trainer_images/default.png', upload_to='trainer_images'),
            preserve_default=False,
        ),
    ]
